### init - 회원가입 성공
POST localhost:9091/users
Content-Type: application/json

{
  "username": "login123",
  "name": "김태훈",
  "email": "qwer@maver.com",
  "phoneNum": "010-1111-1111",
  "password": "12345"
}

### 로그인 실패 - 파라미터 누락
POST localhost:9091/login
Content-Type: application/json

{
  "username": "qwer44"
}

### 로그인 실패 - 존재하지 않는 아이디
POST localhost:9091/login
Content-Type: application/json

{
  "username": "notnotnot",
  "password": "12345"
}

### 로그인 실패 - 비밀번호 오류
POST localhost:9091/login
Content-Type: application/json

{
  "username": "qwer4",
  "password": "aaa"
}