### 회원가입 실패 - 파라미터 누락
POST localhost:9091/members
Content-Type: application/json

{
  "name": "김태훈",
  "email": "qwer@maver.com",
  "phoneNum": "010-1111-1111",
  "password": "12345"
}

### 회원가입 성공
POST localhost:9091/members
Content-Type: application/json

{
  "username": "qwer123",
  "name": "김태훈",
  "email": "qwer@maver.com",
  "phoneNum": "010-1111-1111",
  "password": "12345"
}

### 회원가입 실패 - username 중복
POST localhost:9091/members
Content-Type: application/json

{
  "username": "qwer123",
  "name": "김태훈",
  "email": "poiw@maver.com",
  "phoneNum": "010-1111-1111",
  "password": "12345"
}

### 회원가입 실패 - email 중복
POST localhost:9091/members
Content-Type: application/json

{
  "username": "wowowo",
  "name": "김태훈",
  "email": "qwer@maver.com",
  "phoneNum": "010-1111-1111",
  "password": "12345"
}

### 아이디로 회원정보를 가져온다
GET localhost:9091/members/1/auth-info

### 이메일로 회원정보를 가져온다
GET localhost:9091/members/search?email=qwer@maver.com
